[project]
name = "bike-clasification"
version = "0.1.0"
description = "FastAPI backend for YOLO bike classification"
readme = "README.md"
authors = [
    { name = "tei-cyber", email = "miixd2003@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "pillow",
    "python-multipart",
    "torch",
    "torchvision",
    "ultralytics",
]

[dependency-groups]
dev = [
    "pytest",
    "httpx",
    "ruff",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu121" }
torchvision = { index = "pytorch-cu121" }

[tool.uv]
link-mode = "copy"

[tool.fastapi]
entrypoint = "backend.main:app"